package com.huanglei.wanandroid.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huanglei.wanandroid.model.db.HistoryKeyword;

import com.huanglei.wanandroid.model.db.HistoryKeywordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyKeywordDaoConfig;

    private final HistoryKeywordDao historyKeywordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyKeywordDaoConfig = daoConfigMap.get(HistoryKeywordDao.class).clone();
        historyKeywordDaoConfig.initIdentityScope(type);

        historyKeywordDao = new HistoryKeywordDao(historyKeywordDaoConfig, this);

        registerDao(HistoryKeyword.class, historyKeywordDao);
    }
    
    public void clear() {
        historyKeywordDaoConfig.clearIdentityScope();
    }

    public HistoryKeywordDao getHistoryKeywordDao() {
        return historyKeywordDao;
    }

}
